
// This file has been generated by the GUI designer. Do not modify.
namespace FrackinReserve
{
	public partial class FrackinReserve
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label lblInfo;
		private global::Gtk.Table table2;
		private global::Gtk.ComboBox cbxCompounded;
		private global::Gtk.Label lblBankCanLoan;
		private global::Gtk.Label lblBankHasLoanedOut;
		private global::Gtk.Label lblBanksNextLoan;
		private global::Gtk.Label lblBanksReserves;
		private global::Gtk.Label lblCompounded;
		private global::Gtk.Label lblFractionalResults;
		private global::Gtk.Label lblInitDeposit;
		private global::Gtk.Label lblInitParams;
		private global::Gtk.Label lblInterestOwedParameters;
		private global::Gtk.Label lblInterestPeriods;
		private global::Gtk.Label lblInterestRate;
		private global::Gtk.Label lblInterestResults;
		private global::Gtk.Label lblIterations;
		private global::Gtk.Label lblReserveRequirement;
		private global::Gtk.Label lblTotalInterestAndPrincipal;
		private global::Gtk.Label lblTotalInterestOnly;
		private global::Gtk.Label lblWhatCustomersThink;
		private global::Gtk.SpinButton sbBankCanLoan;
		private global::Gtk.SpinButton sbBankHasLoanedOut;
		private global::Gtk.SpinButton sbBanksNextLoan;
		private global::Gtk.SpinButton sbBanksReserves;
		private global::Gtk.SpinButton sbInitialDeposit;
		private global::Gtk.SpinButton sbInterestPeriods;
		private global::Gtk.SpinButton sbInterestRate;
		private global::Gtk.SpinButton sbIterations;
		private global::Gtk.SpinButton sbReserveRequirement;
		private global::Gtk.SpinButton sbTotalInterestAndPrincipal;
		private global::Gtk.SpinButton sbTotalInterestOnly;
		private global::Gtk.SpinButton sbWhatCustomersThink;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Arrow arrow1;
		private global::Gtk.Fixed fixed1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FrackinReserve.FrackinReserve
			this.Name = "FrackinReserve.FrackinReserve";
			this.Title = global::Mono.Unix.Catalog.GetString ("Frackin\' Reserve - Fractional reserve banking simulator");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DestroyWithParent = true;
			// Container child FrackinReserve.FrackinReserve.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Frackin\' Reserve lets you simulate fractional reserve banking and the resultant c" +
				"ompound interest. "
			);
			this.vbox1.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblInfo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(10));
			this.vbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(17)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.cbxCompounded = global::Gtk.ComboBox.NewText ();
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("Annually"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("Monthly"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("Daily"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("Hourly"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("By the minute"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("By the second"));
			this.cbxCompounded.AppendText (global::Mono.Unix.Catalog.GetString ("By the \"tick\""));
			this.cbxCompounded.Name = "cbxCompounded";
			this.table2.Add (this.cbxCompounded);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbxCompounded]));
			w3.TopAttach = ((uint)(13));
			w3.BottomAttach = ((uint)(14));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XPadding = ((uint)(10));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblBankCanLoan = new global::Gtk.Label ();
			this.lblBankCanLoan.Name = "lblBankCanLoan";
			this.lblBankCanLoan.Xalign = 1F;
			this.lblBankCanLoan.LabelProp = global::Mono.Unix.Catalog.GetString ("What the bank can loan out");
			this.table2.Add (this.lblBankCanLoan);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblBankCanLoan]));
			w4.TopAttach = ((uint)(7));
			w4.BottomAttach = ((uint)(8));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblBankHasLoanedOut = new global::Gtk.Label ();
			this.lblBankHasLoanedOut.Name = "lblBankHasLoanedOut";
			this.lblBankHasLoanedOut.Xalign = 1F;
			this.lblBankHasLoanedOut.LabelProp = global::Mono.Unix.Catalog.GetString ("What the bank has loaned out");
			this.table2.Add (this.lblBankHasLoanedOut);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblBankHasLoanedOut]));
			w5.TopAttach = ((uint)(8));
			w5.BottomAttach = ((uint)(9));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblBanksNextLoan = new global::Gtk.Label ();
			this.lblBanksNextLoan.Name = "lblBanksNextLoan";
			this.lblBanksNextLoan.Xalign = 1F;
			this.lblBanksNextLoan.LabelProp = global::Mono.Unix.Catalog.GetString ("What the bank\'s next loan is");
			this.table2.Add (this.lblBanksNextLoan);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblBanksNextLoan]));
			w6.TopAttach = ((uint)(9));
			w6.BottomAttach = ((uint)(10));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblBanksReserves = new global::Gtk.Label ();
			this.lblBanksReserves.Name = "lblBanksReserves";
			this.lblBanksReserves.Xalign = 1F;
			this.lblBanksReserves.LabelProp = global::Mono.Unix.Catalog.GetString ("What the bank has in reserves");
			this.table2.Add (this.lblBanksReserves);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblBanksReserves]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblCompounded = new global::Gtk.Label ();
			this.lblCompounded.Name = "lblCompounded";
			this.lblCompounded.Xalign = 1F;
			this.lblCompounded.LabelProp = global::Mono.Unix.Catalog.GetString ("Compounded");
			this.table2.Add (this.lblCompounded);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblCompounded]));
			w8.TopAttach = ((uint)(13));
			w8.BottomAttach = ((uint)(14));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblFractionalResults = new global::Gtk.Label ();
			this.lblFractionalResults.Name = "lblFractionalResults";
			this.lblFractionalResults.Xalign = 0F;
			this.lblFractionalResults.LabelProp = global::Mono.Unix.Catalog.GetString ("Fractional Reserve Results on the Money Supply");
			this.table2.Add (this.lblFractionalResults);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblFractionalResults]));
			w9.TopAttach = ((uint)(4));
			w9.BottomAttach = ((uint)(5));
			w9.RightAttach = ((uint)(2));
			w9.XPadding = ((uint)(10));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInitDeposit = new global::Gtk.Label ();
			this.lblInitDeposit.Name = "lblInitDeposit";
			this.lblInitDeposit.Xpad = 1;
			this.lblInitDeposit.Xalign = 1F;
			this.lblInitDeposit.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Deposit");
			this.lblInitDeposit.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.lblInitDeposit);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInitDeposit]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInitParams = new global::Gtk.Label ();
			this.lblInitParams.Name = "lblInitParams";
			this.lblInitParams.Xalign = 0F;
			this.lblInitParams.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Parameters for Fractional Reserve Calculations");
			this.table2.Add (this.lblInitParams);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInitParams]));
			w11.RightAttach = ((uint)(2));
			w11.XPadding = ((uint)(10));
			w11.YPadding = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInterestOwedParameters = new global::Gtk.Label ();
			this.lblInterestOwedParameters.Name = "lblInterestOwedParameters";
			this.lblInterestOwedParameters.Xalign = 0F;
			this.lblInterestOwedParameters.LabelProp = global::Mono.Unix.Catalog.GetString ("Interest Owed Parameters");
			this.table2.Add (this.lblInterestOwedParameters);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInterestOwedParameters]));
			w12.TopAttach = ((uint)(10));
			w12.BottomAttach = ((uint)(11));
			w12.RightAttach = ((uint)(2));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInterestPeriods = new global::Gtk.Label ();
			this.lblInterestPeriods.Name = "lblInterestPeriods";
			this.lblInterestPeriods.Xalign = 1F;
			this.lblInterestPeriods.LabelProp = global::Mono.Unix.Catalog.GetString ("Interest periods (in years)");
			this.table2.Add (this.lblInterestPeriods);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInterestPeriods]));
			w13.TopAttach = ((uint)(11));
			w13.BottomAttach = ((uint)(12));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInterestRate = new global::Gtk.Label ();
			this.lblInterestRate.Name = "lblInterestRate";
			this.lblInterestRate.Xalign = 1F;
			this.lblInterestRate.LabelProp = global::Mono.Unix.Catalog.GetString ("Interest rate (x 100 = %)");
			this.table2.Add (this.lblInterestRate);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInterestRate]));
			w14.TopAttach = ((uint)(12));
			w14.BottomAttach = ((uint)(13));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblInterestResults = new global::Gtk.Label ();
			this.lblInterestResults.Name = "lblInterestResults";
			this.lblInterestResults.Xalign = 0F;
			this.lblInterestResults.LabelProp = global::Mono.Unix.Catalog.GetString ("Interest Owed Results");
			this.table2.Add (this.lblInterestResults);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblInterestResults]));
			w15.TopAttach = ((uint)(14));
			w15.BottomAttach = ((uint)(15));
			w15.RightAttach = ((uint)(2));
			w15.XPadding = ((uint)(10));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblIterations = new global::Gtk.Label ();
			this.lblIterations.Name = "lblIterations";
			this.lblIterations.Xalign = 1F;
			this.lblIterations.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
			this.table2.Add (this.lblIterations);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblIterations]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblReserveRequirement = new global::Gtk.Label ();
			this.lblReserveRequirement.Name = "lblReserveRequirement";
			this.lblReserveRequirement.Xalign = 1F;
			this.lblReserveRequirement.LabelProp = global::Mono.Unix.Catalog.GetString ("Fractional reserve requirement");
			this.table2.Add (this.lblReserveRequirement);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblReserveRequirement]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblTotalInterestAndPrincipal = new global::Gtk.Label ();
			this.lblTotalInterestAndPrincipal.Name = "lblTotalInterestAndPrincipal";
			this.lblTotalInterestAndPrincipal.Xalign = 1F;
			this.lblTotalInterestAndPrincipal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total interest and principal");
			this.table2.Add (this.lblTotalInterestAndPrincipal);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblTotalInterestAndPrincipal]));
			w18.TopAttach = ((uint)(16));
			w18.BottomAttach = ((uint)(17));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblTotalInterestOnly = new global::Gtk.Label ();
			this.lblTotalInterestOnly.Name = "lblTotalInterestOnly";
			this.lblTotalInterestOnly.Xalign = 1F;
			this.lblTotalInterestOnly.LabelProp = global::Mono.Unix.Catalog.GetString ("Total interest on money lent out");
			this.table2.Add (this.lblTotalInterestOnly);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblTotalInterestOnly]));
			w19.TopAttach = ((uint)(15));
			w19.BottomAttach = ((uint)(16));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblWhatCustomersThink = new global::Gtk.Label ();
			this.lblWhatCustomersThink.Name = "lblWhatCustomersThink";
			this.lblWhatCustomersThink.Xalign = 1F;
			this.lblWhatCustomersThink.LabelProp = global::Mono.Unix.Catalog.GetString ("What customers think they have");
			this.table2.Add (this.lblWhatCustomersThink);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblWhatCustomersThink]));
			w20.TopAttach = ((uint)(5));
			w20.BottomAttach = ((uint)(6));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbBankCanLoan = new global::Gtk.SpinButton (0D, 1000000000000D, 1D);
			this.sbBankCanLoan.CanFocus = true;
			this.sbBankCanLoan.Name = "sbBankCanLoan";
			this.sbBankCanLoan.Adjustment.PageIncrement = 10D;
			this.sbBankCanLoan.ClimbRate = 1D;
			this.sbBankCanLoan.Digits = ((uint)(2));
			this.sbBankCanLoan.Numeric = true;
			this.table2.Add (this.sbBankCanLoan);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbBankCanLoan]));
			w21.TopAttach = ((uint)(7));
			w21.BottomAttach = ((uint)(8));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XPadding = ((uint)(10));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbBankHasLoanedOut = new global::Gtk.SpinButton (0D, 1000000000000D, 1D);
			this.sbBankHasLoanedOut.CanFocus = true;
			this.sbBankHasLoanedOut.Name = "sbBankHasLoanedOut";
			this.sbBankHasLoanedOut.Adjustment.PageIncrement = 10D;
			this.sbBankHasLoanedOut.ClimbRate = 1D;
			this.sbBankHasLoanedOut.Digits = ((uint)(2));
			this.sbBankHasLoanedOut.Numeric = true;
			this.table2.Add (this.sbBankHasLoanedOut);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbBankHasLoanedOut]));
			w22.TopAttach = ((uint)(8));
			w22.BottomAttach = ((uint)(9));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XPadding = ((uint)(10));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbBanksNextLoan = new global::Gtk.SpinButton (0D, 1000000000000D, 1D);
			this.sbBanksNextLoan.CanFocus = true;
			this.sbBanksNextLoan.Name = "sbBanksNextLoan";
			this.sbBanksNextLoan.Adjustment.PageIncrement = 10D;
			this.sbBanksNextLoan.ClimbRate = 1D;
			this.sbBanksNextLoan.Digits = ((uint)(2));
			this.sbBanksNextLoan.Numeric = true;
			this.table2.Add (this.sbBanksNextLoan);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbBanksNextLoan]));
			w23.TopAttach = ((uint)(9));
			w23.BottomAttach = ((uint)(10));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XPadding = ((uint)(10));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbBanksReserves = new global::Gtk.SpinButton (0D, 1000000000000D, 1D);
			this.sbBanksReserves.CanFocus = true;
			this.sbBanksReserves.Name = "sbBanksReserves";
			this.sbBanksReserves.Adjustment.PageIncrement = 10D;
			this.sbBanksReserves.ClimbRate = 1D;
			this.sbBanksReserves.Digits = ((uint)(2));
			this.sbBanksReserves.Numeric = true;
			this.table2.Add (this.sbBanksReserves);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbBanksReserves]));
			w24.TopAttach = ((uint)(6));
			w24.BottomAttach = ((uint)(7));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XPadding = ((uint)(10));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbInitialDeposit = new global::Gtk.SpinButton (0D, 100000000D, 100D);
			this.sbInitialDeposit.CanFocus = true;
			this.sbInitialDeposit.Name = "sbInitialDeposit";
			this.sbInitialDeposit.Adjustment.PageIncrement = 100D;
			this.sbInitialDeposit.ClimbRate = 100D;
			this.sbInitialDeposit.Numeric = true;
			this.table2.Add (this.sbInitialDeposit);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbInitialDeposit]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XPadding = ((uint)(10));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.sbInterestPeriods = new global::Gtk.SpinButton (0D, 10000D, 1D);
			this.sbInterestPeriods.CanFocus = true;
			this.sbInterestPeriods.Name = "sbInterestPeriods";
			this.sbInterestPeriods.Adjustment.PageIncrement = 10D;
			this.sbInterestPeriods.ClimbRate = 1D;
			this.sbInterestPeriods.Numeric = true;
			this.table2.Add (this.sbInterestPeriods);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbInterestPeriods]));
			w26.TopAttach = ((uint)(11));
			w26.BottomAttach = ((uint)(12));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XPadding = ((uint)(10));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbInterestRate = new global::Gtk.SpinButton (0D, 100D, 0.01D);
			this.sbInterestRate.CanFocus = true;
			this.sbInterestRate.Name = "sbInterestRate";
			this.sbInterestRate.Adjustment.PageIncrement = 10D;
			this.sbInterestRate.ClimbRate = 1D;
			this.sbInterestRate.Digits = ((uint)(4));
			this.sbInterestRate.Numeric = true;
			this.table2.Add (this.sbInterestRate);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbInterestRate]));
			w27.TopAttach = ((uint)(12));
			w27.BottomAttach = ((uint)(13));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XPadding = ((uint)(10));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbIterations = new global::Gtk.SpinButton (1D, 1000D, 1D);
			this.sbIterations.CanFocus = true;
			this.sbIterations.Name = "sbIterations";
			this.sbIterations.Adjustment.PageIncrement = 10D;
			this.sbIterations.ClimbRate = 1D;
			this.sbIterations.Numeric = true;
			this.sbIterations.Value = 1D;
			this.table2.Add (this.sbIterations);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbIterations]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XPadding = ((uint)(10));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbReserveRequirement = new global::Gtk.SpinButton (0D, 1D, 0.01D);
			this.sbReserveRequirement.CanFocus = true;
			this.sbReserveRequirement.Name = "sbReserveRequirement";
			this.sbReserveRequirement.Adjustment.PageIncrement = 0.01D;
			this.sbReserveRequirement.ClimbRate = 1D;
			this.sbReserveRequirement.Digits = ((uint)(7));
			this.sbReserveRequirement.Numeric = true;
			this.table2.Add (this.sbReserveRequirement);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbReserveRequirement]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XPadding = ((uint)(10));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbTotalInterestAndPrincipal = new global::Gtk.SpinButton (0D, 100000000000D, 1D);
			this.sbTotalInterestAndPrincipal.CanFocus = true;
			this.sbTotalInterestAndPrincipal.Name = "sbTotalInterestAndPrincipal";
			this.sbTotalInterestAndPrincipal.Adjustment.PageIncrement = 10D;
			this.sbTotalInterestAndPrincipal.ClimbRate = 1D;
			this.sbTotalInterestAndPrincipal.Digits = ((uint)(2));
			this.sbTotalInterestAndPrincipal.Numeric = true;
			this.table2.Add (this.sbTotalInterestAndPrincipal);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbTotalInterestAndPrincipal]));
			w30.TopAttach = ((uint)(16));
			w30.BottomAttach = ((uint)(17));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XPadding = ((uint)(10));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbTotalInterestOnly = new global::Gtk.SpinButton (0D, 10000000000D, 1D);
			this.sbTotalInterestOnly.CanFocus = true;
			this.sbTotalInterestOnly.Name = "sbTotalInterestOnly";
			this.sbTotalInterestOnly.Adjustment.PageIncrement = 10D;
			this.sbTotalInterestOnly.ClimbRate = 1D;
			this.sbTotalInterestOnly.Digits = ((uint)(2));
			this.sbTotalInterestOnly.Numeric = true;
			this.table2.Add (this.sbTotalInterestOnly);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbTotalInterestOnly]));
			w31.TopAttach = ((uint)(15));
			w31.BottomAttach = ((uint)(16));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XPadding = ((uint)(10));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbWhatCustomersThink = new global::Gtk.SpinButton (0D, 1000000000000D, 1D);
			this.sbWhatCustomersThink.CanFocus = true;
			this.sbWhatCustomersThink.Name = "sbWhatCustomersThink";
			this.sbWhatCustomersThink.Adjustment.PageIncrement = 10D;
			this.sbWhatCustomersThink.ClimbRate = 1D;
			this.sbWhatCustomersThink.Digits = ((uint)(2));
			this.sbWhatCustomersThink.Numeric = true;
			this.table2.Add (this.sbWhatCustomersThink);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbWhatCustomersThink]));
			w32.TopAttach = ((uint)(5));
			w32.BottomAttach = ((uint)(6));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XPadding = ((uint)(10));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.arrow1 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
			this.arrow1.Name = "arrow1";
			this.hbox2.Add (this.arrow1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.arrow1]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
			w35.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 528;
			this.DefaultHeight = 576;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.sbReserveRequirement.ValueChanged += new global::System.EventHandler (this.OnSbReserveRequirementValueChanged);
			this.sbIterations.ValueChanged += new global::System.EventHandler (this.OnSbIterationsValueChanged);
			this.sbInterestRate.ValueChanged += new global::System.EventHandler (this.OnSbInterestRateValueChanged);
			this.sbInterestPeriods.ValueChanged += new global::System.EventHandler (this.OnSbInterestPeriodsValueChanged);
			this.sbInitialDeposit.ValueChanged += new global::System.EventHandler (this.InitialDepositChanged);
			this.cbxCompounded.Changed += new global::System.EventHandler (this.OnCbxCompoundedChanged);
		}
	}
}
